name: Deploy library

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release-package:
    if: github.repository == 'Jagirhussan/ftuutils'
    runs-on: ubuntu-20.04
    name: Release package
    permissions:
      contents: write
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          pypi-package-name: ftuutils
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/          
